# èµ·å§‹ URLï¼ˆæ¢æˆæ‚¨è‡ªå·±çš„åŸŸåï¼‰
baseURL = "https://jtshong.com"
# ç½‘ç«™æ ‡é¢˜
title = "jtshong"
# æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
pagination.pagerSize = 7
# ä¸»é¢˜åç§°
theme = "PaperMod"
# è¯­è¨€ä»£ç ï¼ˆzh-ç®€ä½“ä¸­æ–‡ï¼‰
languageCode = "en-us"
DefaultContentLanguage = "en"
# æ˜¯å¦æœ‰ CJK è¯­è¨€ï¼ˆä¸­-æ—¥-éŸ©ï¼‰
hasCJKLanguage = true

# æ˜¯å¦ç”Ÿæˆ robots.txt
enableRobotsTXT = true

# æ˜¯å¦æ„å»ºè‰ç¨¿
buildDrafts = false
# æ˜¯å¦æ„å»ºæœªæ¥çš„æ–‡ç« 
buildFuture = false
# æ˜¯å¦æ„å»ºè¿‡æœŸçš„æ–‡ç« 
buildExpired = false
# æ˜¯å¦å¯ç”¨ Emoji
enableEmoji = true
# æ˜¯å¦å¯ç”¨ Git ä¿¡æ¯
enableGitInfo = false

# Google Analytics ID
# googleAnalytics = ""

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "jtshong"
  description = "Scott Hong's PW"
  author = "Scott hong"
  # images: List
  images = ["opengraph.webp"]
  DateFormat = "2006-01-02"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.assets]
  # disableHLJS = true
  # disableFingerprinting = true
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

[params.label]
  text = "jtshong"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

[params.profileMode]
  enabled = true
  title = "Jingtao Scott Hong"
  subtitle = "This is subtitle"
  imageUrl = "menu/me.jpg"
  imageWidth = 200
  imageHeight = 200
  imageTitle = "my image"

[[params.profileMode.buttons]]
  name = "Projects"
  url = "projects"

[[params.profileMode.buttons]]
  name = "Art"
  url = "arts"

# [params.homeInfoParams]
#   Title = "Hi there ğŸ‘‹"
#   Content = "Welcome to hugo start, this is a example of Hugo and PaperMod"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/jts-hong"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jtshong/"

[params.analytics.google]
  SiteVerificationTag = ""

[params.analytics.bing]
  SiteVerificationTag = ""

[params.analytics.yandex]
  SiteVerificationTag = ""

[params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

[params.editPost]
  URL = "https://github.com/DejavuMoe/hugo-start/edit/master/content/posts"
  Text = "Edit on GitHub"
  appendFilePath = true

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[menu]
  [[menu.main]]
    identifier = "Menu"
    name = "Menu"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "Arts"
    name = "Arts"
    url = "/arts/"
    weight = 20

  [[menu.main]]
    identifier = "Github"
    name = "Github"
    url = "https://github.com/"
    weight = 30

[markup.highlight]
  noClasses = false

[privacy.vimeo]
  disabled = true
  enableDNT = true
  simple = true

[privacy.twitter]
  disabled = true
  enableDNT = true
  simple = true

[privacy.instagram]
  disabled = true
  simple = true

[privacy.youtube]
  disabled = true
  privacyEnhanced = true

[services.instagram]
  disableInlineCSS = true

[services.twitter]
  disableInlineCSS = true